config/routes.rb
Rails.application.routes.draw do
  resources :cocktails do
    resources :doses, only: [:new, :create]
    resources :reviews, only: [:new, :create]
  end
  resources :doses, only: [:destroy]
  resources :reviews, only: [:destroy]
  root to: "cocktails#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :ingredients, through: :doses

  validates :name, presence: true, uniqueness: true
  validates :photo, presence: true

  mount_uploader :photo, PhotoUploader

  include PgSearch

  pg_search_scope :search,
   against: [
     [:name, 'A'],
     [:description, 'B']
   ],
   using: {
   tsearch: { prefix: true }
   }
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates_uniqueness_of :cocktail, scope: [:ingredient]
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  
  validates :name, presence: true, uniqueness: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :cocktail

  validates :content, presence: true
  validates :stars, numericality: {only_integer: true}
  validates :stars, inclusion: { in: [0, 1, 2, 3, 4, 5] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show, :edit, :update, :destroy]

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)

    if @cocktail.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @cocktail.update(cocktail_params)
    redirect_to cocktail_path
  end

  def destroy
    @cocktail.destroy
    redirect_to root_path
  end

  def index
    if params[:query].present?
      @cocktails = Cocktail.search(params[:query])
    else
      @cocktails = Cocktail.all
    end
  end

  def show
    @dose = Dose.new
    @review = Review.new
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :description, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_cocktail, only: [:new, :create]

  def new
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail_id = @cocktail.id

    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render 'cocktails/show'
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @cocktail = @dose.cocktail
    @dose.destroy
    redirect_to cocktail_path(@cocktail)
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def dose_params
    params.require(:dose).permit(:name, :description, :ingredient_id, :cocktail_id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_cocktail, only: [:new, :create]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.cocktail_id = @cocktail.id

    if @review.save
      redirect_to cocktail_path(@cocktail)
    else
      render 'cocktails/show'
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @cocktail = Review.find(params[:id]).cocktail_id
    @review.destroy
    redirect_to cocktail_path(@cocktail)
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def review_params
    params.require(:review).permit(:stars, :content, :cocktail_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
  def cocktail_image_path_for(cocktail)
    cl_image_path cocktail.photo
  end

  def average(cocktail)
    if !cocktail.reviews.empty?
      @stars = []
      cocktail.reviews.each { |review| @stars << review.stars }
      @stars.inject(&:+) / @stars.size
    else
      0
    end
  end
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cocktails/_cocktail-form.html.erb
<%= simple_form_for(@cocktail) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-inputs">
    <%= f.input :description %>
  </div>

  <div class="form-inputs">
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn--primary" %>
  </div>
<% end %>

app/views/cocktails/_cocktail.html.erb
<%= link_to(cocktail_path(cocktail), class: "cocktail__item", style: "background-image: url(#{cocktail_image_path_for(cocktail)})") do %>
  <h2 class="cocktail__name"><%= cocktail.name %></h2>
  <div class="cocktail__average">
    <% if average(cocktail) != 0 %>
      <% average(cocktail).times do %>
        <%= icon('fas star--full', 'star') %>
      <% end %>
      <% (5 - average(cocktail)).times do %>
        <%= icon('fas star--empty', 'star') %>
      <% end %>
    <% else %>
      <p>No reviews yet</p>
    <% end %>
  </div>
  <span class="cocktail__filter"></span>
<% end %>

app/views/cocktails/edit.html.erb
<div class="container">

  <h1>Edit <%= @cocktail.name %></h1>

  <%= render "cocktail-form" %>

</div>

app/views/cocktails/index.html.erb
<div class="banner home__banner">
  <div class="container">
    <h1>All you need is Cocktails</h1>
  </div>
</div>

<div class="container">

  <div class="row cocktail__list">
    <% @cocktails.each do |cocktail| %>
      <div class="cocktail col-md-3">
        <%= render "cocktail", cocktail: cocktail %>
      </div>
    <% end %>
  </div>

</div>

app/views/cocktails/new.html.erb
<div class="container">

  <h1>Add a cocktail</h1>

  <%= simple_form_for(@cocktail) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :name %>
    </div>

    <div class="form-inputs">
      <%= f.input :photo %>
      <%= f.input :photo_cache, as: :hidden %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, class: "btn btn--primary" %>
    </div>
  <% end %>

</div>

app/views/cocktails/show.html.erb
<div class="banner cocktail__banner" style="background-image: linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url(<%= cocktail_image_path_for(@cocktail) %>)">
  <div class="container">
    <h1 class="cocktail__name"><%= @cocktail.name %></h1>
    <% if @cocktail.description %>
      <p class="cocktail__description"><%= @cocktail.description %></p>
    <% end %>
  </div>
  <div class="cocktail__actions">
    <%= link_to(edit_cocktail_path(@cocktail), class: "btn btn--secondary") do %>
      <%= icon('fas', 'edit') %>Edit
    <% end %>
    <%= link_to(cocktail_path(@cocktail), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn--secondary") do %>
      <%= icon('fas', 'trash') %>Delete
    <% end %>
  </div>
</div>

<div class="row cocktail__ingredients">
  <div class="container">

    <div class="col-lg-6 ingredients__list">
      <h2>Ingredients</h2>
      <% @cocktail.doses.each do |dose| %>
        <p class="ingredients__item">
          <strong><%= dose.ingredient.name %></strong>
          -
          <%= dose.description %>
          (
            <%= link_to(dose_path(dose), method: :delete, data: { confirm: "Are you sure?" }) do %>
              <%= icon('fas', 'trash') %>
            <% end %>
          )
        </p>
      <% end %>
    </div>

    <div class="col-lg-6 ingredients__add">
      <h2>Add an ingredient</h2>
      <%= simple_form_for [@cocktail, @dose] do |f| %>
        <%= f.association :ingredient, include_blank: false, collection: Ingredient.order(:name) %>
        <%= f.input :description %>
        <%= f.submit "Add ingredient", class: "btn btn--primary" %>
      <% end %>
    </div>

  </div>
</div>

<div class="row cocktail__reviews">
  <div class="container">

    <div class="col-lg-12 reviews__list">
      <h2>Reviews</h2>

      <div class="row">
        <% @cocktail.reviews.each do |review| %>
        <div class="review col-lg-3">
          <div class="review__stars">
            <% review.stars.times do %>
              <%= icon('fas star--full', 'star') %>
            <% end %>
            <% (5 - review.stars).times do %>
              <%= icon('fas star--empty', 'star') %>
            <% end %>
          </div>
          <p class="eview__content"><%= review.content %></p>
          <%= link_to(review_path(review), method: :delete, data: { confirm: "Are you sure?" }, class: "review__delete") do %>
            <%= icon('fas', 'trash') %>Delete this review
          <% end %>
        </div>
        <% end %>
      </div>
    </div>

    <div class="col-lg-12 reviews__add">
      <h2>Add a review</h2>
      <%= simple_form_for [@cocktail, @review] do |f| %>
        <%= f.input :stars, collection: [0, 1, 2, 3, 4, 5], include_blank: false %>
        <%= f.input :content %>
        <%= f.submit "Add review", class: "btn btn--primary" %>
      <% end %>
    </div>

  </div>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <p>This tiny app was made with <%= icon('fas', 'heart') %> at <a href="https://www.lewagon.com/fr/lyon" target="_blank">Le Wagon Lyon</a> by <a href="http://www.etiennedelorieux.com" target="_blank">Etienne Delorieux</a></p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <%= link_to "Cocktailab", root_path, class: "logo" %>

  <%= form_tag cocktails_path, method: :get do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Find a cocktail"
    %>
  <% end %>
  
  <%= link_to(new_cocktail_path, id: "new-cocktail", class: "btn btn--primary") do %>
    <%= icon('fas', 'plus') %>New Mixture
  <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cocktailab</title>
    <%= csrf_meta_tags %>

    <%= favicon_link_tag 'favicon.png' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= stylesheet_pack_tag 'application' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="wrapper">
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>

    <script
  src="https://code.jquery.com/jquery-3.3.1.min.js"
  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous"></script>
  <%= javascript_pack_tag "application" %>
  </body>
</html>